# Generated by Django 3.2.4 on 2021-10-03 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_elementos', models.IntegerField()),
                ('dt_cadastro', models.DateTimeField()),
                ('dt_atualizacao', models.DateTimeField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tensao_mag', models.IntegerField()),
                ('tensao_ang', models.IntegerField()),
                ('corrente_mag', models.IntegerField()),
                ('corrente_ang', models.IntegerField()),
                ('imp_0_real', models.IntegerField()),
                ('imp_0_imag', models.IntegerField()),
                ('imp_1_real', models.IntegerField()),
                ('imp_1_imag', models.IntegerField()),
                ('tp_elemento', models.CharField(choices=[('T', 'Transformador'), ('L', 'Linha'), ('F', 'Fonte'), ('B', 'Barra')], max_length=1)),
                ('dt_cadastro', models.DateTimeField()),
                ('dt_atualizacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Circuito_elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_circuito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicial.circuito')),
                ('id_elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicial.elemento')),
            ],
        ),
    ]
